"use client";

import { Dices, TriangleAlert } from "lucide-react";
import { scaleLinear } from "d3-scale";
import { area, line } from "d3-shape";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";

import { Axis, ticksFrom } from "@/components/charts/primitives/Axis";
import { ChartFrame } from "@/components/charts/primitives/ChartFrame";
import { DataTable, type DataTableColumn } from "@/components/charts/primitives/DataTable";
import { Legend, type LegendItem } from "@/components/charts/primitives/Legend";
import { isNarrow, useChartSize } from "@/components/charts/primitives/useChartSize";
import { useKeyboardNav } from "@/components/charts/primitives/useKeyboardNav";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { cn } from "@/lib/cn";
import { formatPercent } from "@/lib/format";
import { HHI_HIGHLY_CONCENTRATED } from "@/lib/hhi";
import { nextSeed } from "@/lib/prng";
import {
  OTHER_SERIES_ID,
  SIMULATION_PRESETS,
  SIMULATOR_DISCLAIMER,
  normalizeParams,
  runSimulation,
  type SimulationParams,
  type SimulationResult,
} from "@/lib/simulation";
import {
  parseAtlasState,
  serializeAtlasState,
  updateAtlasState,
  type AtlasState,
} from "@/lib/url-state";

/** The reruns are debounced so dragging a slider does not run 60 ticks per frame. */
const RERUN_DEBOUNCE_MS = 150;

/** How long to wait after the last control change before rewriting the URL. */
const URL_DEBOUNCE_MS = 200;

const MARGIN = { top: 14, right: 54, bottom: 30, left: 56 };
const NARROW_MARGIN = { top: 14, right: 40, bottom: 30, left: 42 };
const SHARES_HEIGHT = 186;
const HHI_HEIGHT = 168;
const PANEL_GAP = 46;

const SERIES_COLORS = [
  "var(--cat-horizontal)",
  "var(--cat-infrastructure)",
  "var(--cat-vertical)",
  "var(--cat-consumer)",
  "var(--cat-emerging)",
  "var(--cat-horizontal)",
  "var(--cat-infrastructure)",
  "var(--cat-vertical)",
] as const;

const OTHER_COLOR = "var(--muted-foreground)";
const HHI_COLOR = "var(--cat-emerging)";
const TOP3_COLOR = "var(--cat-vertical)";

const seriesColor = (id: string, index: number): string => {
  if (id === OTHER_SERIES_ID) return OTHER_COLOR;
  return SERIES_COLORS[index % SERIES_COLORS.length] ?? OTHER_COLOR;
};

const seriesOpacity = (id: string, index: number): number => {
  if (id === OTHER_SERIES_ID) return 0.3;
  if (index < SERIES_COLORS.length / 2) return 0.85;
  return 0.5;
};

const formatHhi = (value: number): string => Math.round(value).toLocaleString("en-US");

/**
 * The "not a prediction" banner, shared so the route shell and a Story embed
 * render exactly the same thing. `SimulatorChart` repeats the sentence as its
 * `ChartFrame` footnote, so no rendering of the model is ever unlabelled.
 */
export const SimulatorDisclaimer = (): React.ReactElement => (
  <p
    role="note"
    className="flex items-start gap-2 rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-foreground"
  >
    <TriangleAlert aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-destructive" />
    <span>
      <strong className="font-semibold">{SIMULATOR_DISCLAIMER}</strong> Every number below is
      generated by the model on this page, not observed in the world.
    </span>
  </p>
);

type StackBand = { tick: number; y0: number; y1: number };

type StackedSeries = {
  id: string;
  label: string;
  color: string;
  opacity: number;
  band: StackBand[];
};

type TickMark = { id: string; tick: number };

export type SimulatorChartProps = {
  result: SimulationResult;
  params: SimulationParams;
};

/**
 * Three views of the same run, sharing one x axis: stacked shares on top, then
 * HHI against the US DOJ/FTC 2023 "highly concentrated" threshold with the
 * top-three share on the right axis. Platform shifts are marked on both panels.
 */
export const SimulatorChart = ({ result, params }: SimulatorChartProps): React.ReactElement => {
  const { ref, size } = useChartSize({ initial: { width: 760, height: 460 } });
  const [hoverTick, setHoverTick] = useState<number | null>(null);
  const [focusedTick, setFocusedTick] = useState<number | null>(null);
  const [pinnedTick, setPinnedTick] = useState<number | null>(null);

  const narrow = isNarrow(size.width);
  const margin = narrow ? NARROW_MARGIN : MARGIN;
  const innerWidth = Math.max(80, size.width - margin.left - margin.right);
  const totalHeight = margin.top + SHARES_HEIGHT + PANEL_GAP + HHI_HEIGHT + margin.bottom;
  const hhiTop = margin.top + SHARES_HEIGHT + PANEL_GAP;

  const tickCount = result.hhiSeries.length;
  const lastTick = tickCount;
  const shiftSet = useMemo(() => new Set(result.shiftTicks), [result.shiftTicks]);

  const xScale = useMemo(
    () => scaleLinear().domain([1, Math.max(2, lastTick)]).range([0, innerWidth]),
    [innerWidth, lastTick],
  );

  const shareScale = useMemo(
    () => scaleLinear().domain([0, 1]).range([SHARES_HEIGHT, 0]),
    [],
  );

  const hhiMax = useMemo(() => {
    const peak = result.hhiSeries.reduce((max, point) => Math.max(max, point.value), 0);
    return Math.min(10000, Math.max(2400, Math.ceil((peak * 1.12) / 500) * 500));
  }, [result.hhiSeries]);

  const hhiScale = useMemo(
    () => scaleLinear().domain([0, hhiMax]).range([HHI_HEIGHT, 0]),
    [hhiMax],
  );

  const top3Scale = useMemo(
    () => scaleLinear().domain([0, 100]).range([HHI_HEIGHT, 0]),
    [],
  );

  const stacked = useMemo<StackedSeries[]>(() => {
    const offsets = new Array<number>(tickCount).fill(0);
    return result.shareSeries.map((series, index) => {
      const band = series.values.map((value, position) => {
        const y0 = offsets[position] ?? 0;
        const y1 = y0 + value;
        offsets[position] = y1;
        return { tick: position + 1, y0, y1 };
      });
      return {
        id: series.id,
        label: series.label,
        color: seriesColor(series.id, index),
        opacity: seriesOpacity(series.id, index),
        band,
      };
    });
  }, [result.shareSeries, tickCount]);

  const areaPath = useMemo(
    () =>
      area<StackBand>()
        .x((band) => xScale(band.tick))
        .y0((band) => shareScale(band.y0))
        .y1((band) => shareScale(band.y1)),
    [shareScale, xScale],
  );

  const hhiPath = useMemo(() => {
    const builder = line<{ tick: number; value: number }>()
      .x((point) => xScale(point.tick))
      .y((point) => hhiScale(point.value));
    return builder([...result.hhiSeries]) ?? "";
  }, [hhiScale, result.hhiSeries, xScale]);

  const top3Path = useMemo(() => {
    const builder = line<{ tick: number; value: number }>()
      .x((point) => xScale(point.tick))
      .y((point) => top3Scale(point.value));
    return builder([...result.top3Series]) ?? "";
  }, [result.top3Series, top3Scale, xScale]);

  const tickMarks = useMemo<TickMark[]>(
    () => result.hhiSeries.map((point) => ({ id: `tick-${point.tick}`, tick: point.tick })),
    [result.hhiSeries],
  );

  const handleActivate = useCallback((mark: TickMark): void => {
    setPinnedTick((current) => (current === mark.tick ? null : mark.tick));
  }, []);

  const handleFocusChange = useCallback((mark: TickMark): void => {
    setFocusedTick(mark.tick);
  }, []);

  const nav = useKeyboardNav<TickMark>({
    items: tickMarks,
    getId: (mark) => mark.id,
    orientation: "horizontal",
    onActivate: handleActivate,
    onFocusChange: handleFocusChange,
  });

  const readoutTick = hoverTick ?? focusedTick ?? pinnedTick ?? lastTick;
  const readoutIndex = readoutTick - 1;
  const readoutHhi = result.hhiSeries[readoutIndex]?.value ?? 0;
  const readoutTop3 = result.top3Series[readoutIndex]?.value ?? 0;
  const readoutLeader = stacked.reduce((max, series) => {
    const value = series.band[readoutIndex];
    if (!value || series.id === OTHER_SERIES_ID) return max;
    return Math.max(max, value.y1 - value.y0);
  }, 0);

  const describeTick = useCallback(
    (tick: number): string => {
      const hhi = result.hhiSeries[tick - 1]?.value ?? 0;
      const top3 = result.top3Series[tick - 1]?.value ?? 0;
      const shift = shiftSet.has(tick) ? ", platform shift on this tick" : "";
      return `Tick ${tick}: HHI ${formatHhi(hhi)}, top three share ${formatPercent(top3, 0)}${shift}. Press Enter to pin this tick.`;
    },
    [result.hhiSeries, result.top3Series, shiftSet],
  );

  const legendItems = useMemo<LegendItem[]>(
    () => [
      ...stacked.map((series) => ({
        id: series.id,
        label: series.label,
        color: series.color,
      })),
      { id: "hhi-line", label: "HHI (right panel, left axis)", color: HHI_COLOR },
      { id: "top3-line", label: "Top-3 share", color: TOP3_COLOR, dashed: true },
    ],
    [stacked],
  );

  const xTicks = useMemo(
    () => ticksFrom(xScale, narrow ? 4 : 8, (value) => String(Math.round(value))),
    [narrow, xScale],
  );
  const shareTicks = useMemo(
    () => ticksFrom(shareScale, 4, (value) => `${Math.round(value * 100)}%`),
    [shareScale],
  );
  const hhiTicks = useMemo(
    () => ticksFrom(hhiScale, 4, (value) => formatHhi(value)),
    [hhiScale],
  );
  const top3Ticks = useMemo(
    () => ticksFrom(top3Scale, 4, (value) => `${Math.round(value)}%`),
    [top3Scale],
  );

  const bandWidth = innerWidth / Math.max(1, tickCount - 1);
  const crosshairX = xScale(readoutTick);

  const tableColumns: DataTableColumn<{ tick: number }>[] = useMemo(() => {
    const columns: DataTableColumn<{ tick: number }>[] = [
      { key: "tick", header: "Tick", render: (row) => String(row.tick), numeric: true },
      {
        key: "hhi",
        header: "HHI",
        align: "right",
        numeric: true,
        render: (row) => formatHhi(result.hhiSeries[row.tick - 1]?.value ?? 0),
      },
      {
        key: "top3",
        header: "Top-3 share",
        align: "right",
        numeric: true,
        render: (row) => formatPercent(result.top3Series[row.tick - 1]?.value ?? 0, 1),
      },
    ];

    for (const series of stacked) {
      columns.push({
        key: series.id,
        header: series.label,
        align: "right",
        numeric: true,
        render: (row) => {
          const band = series.band[row.tick - 1];
          if (!band) return "—";
          return formatPercent((band.y1 - band.y0) * 100, 1);
        },
      });
    }

    columns.push({
      key: "shift",
      header: "Platform shift",
      render: (row) => (shiftSet.has(row.tick) ? "Yes" : "—"),
    });

    return columns;
  }, [result.hhiSeries, result.top3Series, shiftSet, stacked]);

  const tableRows = useMemo(() => tickMarks.map((mark) => ({ tick: mark.tick })), [tickMarks]);

  const takeaway =
    result.shiftTicks.length > 0
      ? `This run ended at HHI ${formatHhi(result.hhiSeries[lastTick - 1]?.value ?? 0)} after ${result.shiftTicks.length} platform shift${result.shiftTicks.length === 1 ? "" : "s"}.`
      : `This run ended at HHI ${formatHhi(result.hhiSeries[lastTick - 1]?.value ?? 0)} with no platform shift.`;

  return (
    <ChartFrame
      title="Simulated market concentration over 60 ticks"
      takeaway={takeaway}
      source={`Modeled: Atlas toy simulation, seed ${params.seed}. Concentration thresholds from the US DOJ/FTC 2023 Merger Guidelines.`}
      footnote={SIMULATOR_DISCLAIMER}
      table={
        <DataTable
          caption="Simulated HHI, top-three share and per-firm shares for every tick of the run"
          columns={tableColumns}
          rows={tableRows}
          getRowKey={(row) => `tick-${row.tick}`}
          getConfidence={() => ({
            confidence: "modeled",
            note: "Generated by the Atlas toy simulation; no real market is being described.",
          })}
        />
      }
    >
      {({ animate }) => (
        <div className="flex flex-col gap-3">
          <div
            className="flex flex-wrap items-center gap-x-4 gap-y-1 rounded-md bg-secondary/60 px-3 py-2 text-xs"
            aria-live="polite"
          >
            <span className="font-medium">Tick {readoutTick}</span>
            <span className="text-muted-foreground">
              HHI <span className="font-mono text-foreground">{formatHhi(readoutHhi)}</span>
            </span>
            <span className="text-muted-foreground">
              Top 3 <span className="font-mono text-foreground">{formatPercent(readoutTop3, 1)}</span>
            </span>
            <span className="text-muted-foreground">
              Largest firm{" "}
              <span className="font-mono text-foreground">
                {formatPercent(readoutLeader * 100, 1)}
              </span>
            </span>
            {shiftSet.has(readoutTick) ? (
              <span className="font-medium text-destructive">Platform shift</span>
            ) : null}
          </div>

          <div ref={ref} className="w-full">
            <svg
              width={size.width}
              height={totalHeight}
              viewBox={`0 0 ${size.width} ${totalHeight}`}
              role="img"
              aria-label={`Simulated market: stacked firm shares, Herfindahl-Hirschman Index and top-three share across ${tickCount} ticks. ${takeaway}`}
              className="max-w-full touch-none"
              onMouseLeave={() => setHoverTick(null)}
            >
              <g transform={`translate(${margin.left}, ${margin.top})`}>
                <Axis
                  orientation="left"
                  ticks={shareTicks}
                  scale={(value) => shareScale(value)}
                  length={innerWidth}
                  showGrid
                  label={narrow ? undefined : "Share"}
                />
                <g transform={`translate(0, ${SHARES_HEIGHT})`}>
                  <Axis
                    orientation="bottom"
                    ticks={xTicks}
                    scale={(value) => xScale(value)}
                    length={innerWidth}
                  />
                </g>

                {stacked.map((series) => (
                  <path
                    key={series.id}
                    d={areaPath(series.band) ?? ""}
                    fill={series.color}
                    fillOpacity={series.opacity}
                    stroke={series.color}
                    strokeWidth={0.5}
                    className={cn({ "transition-opacity duration-300": animate })}
                  />
                ))}

                {result.shiftTicks.map((tick) => (
                  <g key={`shift-shares-${tick}`} aria-hidden="true">
                    <line
                      x1={xScale(tick)}
                      x2={xScale(tick)}
                      y1={-6}
                      y2={SHARES_HEIGHT}
                      className="stroke-destructive"
                      strokeWidth={1}
                      strokeDasharray="3 3"
                      opacity={0.8}
                    />
                    <path
                      d={`M ${xScale(tick) - 4} -6 L ${xScale(tick) + 4} -6 L ${xScale(tick)} 1 Z`}
                      className="fill-destructive"
                    />
                  </g>
                ))}
              </g>

              <g transform={`translate(${margin.left}, ${hhiTop})`}>
                <Axis
                  orientation="left"
                  ticks={hhiTicks}
                  scale={(value) => hhiScale(value)}
                  length={innerWidth}
                  showGrid
                  label={narrow ? undefined : "HHI"}
                />
                <g transform={`translate(${innerWidth}, 0)`}>
                  <Axis
                    orientation="right"
                    ticks={top3Ticks}
                    scale={(value) => top3Scale(value)}
                    length={innerWidth}
                  />
                </g>
                <g transform={`translate(0, ${HHI_HEIGHT})`}>
                  <Axis
                    orientation="bottom"
                    ticks={xTicks}
                    scale={(value) => xScale(value)}
                    length={innerWidth}
                    label="Tick"
                  />
                </g>

                {hhiMax >= HHI_HIGHLY_CONCENTRATED ? (
                  <g aria-hidden="true">
                    <line
                      x1={0}
                      x2={innerWidth}
                      y1={hhiScale(HHI_HIGHLY_CONCENTRATED)}
                      y2={hhiScale(HHI_HIGHLY_CONCENTRATED)}
                      className="stroke-foreground"
                      strokeWidth={1}
                      strokeDasharray="6 4"
                      opacity={0.65}
                    />
                    <text
                      x={4}
                      y={hhiScale(HHI_HIGHLY_CONCENTRATED) - 6}
                      className="fill-muted-foreground text-[11px]"
                    >
                      {narrow
                        ? "HHI 1,800 — highly concentrated"
                        : "HHI 1,800 — “highly concentrated” (US DOJ/FTC 2023 Merger Guidelines)"}
                    </text>
                  </g>
                ) : null}

                {result.shiftTicks.map((tick) => (
                  <line
                    key={`shift-hhi-${tick}`}
                    aria-hidden="true"
                    x1={xScale(tick)}
                    x2={xScale(tick)}
                    y1={0}
                    y2={HHI_HEIGHT}
                    className="stroke-destructive"
                    strokeWidth={1}
                    strokeDasharray="3 3"
                    opacity={0.8}
                  />
                ))}

                <path
                  d={top3Path}
                  fill="none"
                  stroke={TOP3_COLOR}
                  strokeWidth={1.75}
                  strokeDasharray="5 3"
                />
                <path d={hhiPath} fill="none" stroke={HHI_COLOR} strokeWidth={2} />
              </g>

              <g transform={`translate(${margin.left}, ${margin.top})`}>
                <line
                  aria-hidden="true"
                  x1={crosshairX}
                  x2={crosshairX}
                  y1={0}
                  y2={SHARES_HEIGHT + PANEL_GAP + HHI_HEIGHT}
                  className="stroke-foreground"
                  strokeWidth={1}
                  opacity={0.35}
                />
                {tickMarks.map((mark) => (
                  <rect
                    key={mark.id}
                    ref={nav.registerMark(mark.id)}
                    x={xScale(mark.tick) - bandWidth / 2}
                    y={0}
                    width={Math.max(2, bandWidth)}
                    height={SHARES_HEIGHT + PANEL_GAP + HHI_HEIGHT}
                    fill="transparent"
                    tabIndex={nav.getTabIndex(mark)}
                    role="button"
                    aria-label={describeTick(mark.tick)}
                    aria-pressed={pinnedTick === mark.tick}
                    className="cursor-pointer outline-none focus-visible:stroke-ring focus-visible:[stroke-width:2]"
                    onMouseEnter={() => setHoverTick(mark.tick)}
                    onFocus={() => {
                      nav.handleFocus(mark);
                      setFocusedTick(mark.tick);
                    }}
                    onBlur={() => setFocusedTick(null)}
                    onClick={() => handleActivate(mark)}
                    onKeyDown={(event) => nav.handleKeyDown(event, mark)}
                  />
                ))}
              </g>
            </svg>
          </div>

          <Legend items={legendItems} title="Series" />
        </div>
      )}
    </ChartFrame>
  );
};

type SliderControlProps = {
  id: string;
  label: string;
  hint: string;
  value: number;
  min: number;
  max: number;
  step: number;
  display: string;
  onChange: (value: number) => void;
};

const SliderControl = ({
  id,
  label,
  hint,
  value,
  min,
  max,
  step,
  display,
  onChange,
}: SliderControlProps): React.ReactElement => {
  const handleValueChange = (next: number[]): void => {
    const candidate = next[0];
    if (candidate === undefined) return;
    onChange(candidate);
  };

  return (
    <div role="group" aria-labelledby={`${id}-label`} className="flex flex-col gap-1.5">
      <div className="flex items-baseline justify-between gap-2">
        <Label id={`${id}-label`} htmlFor={id} className="text-sm">
          {label}
        </Label>
        <span className="font-mono text-xs tabular-nums text-muted-foreground">{display}</span>
      </div>
      <Slider
        id={id}
        aria-labelledby={`${id}-label`}
        aria-label={`${label}: ${display}`}
        aria-valuetext={display}
        value={[value]}
        min={min}
        max={max}
        step={step}
        onValueChange={handleValueChange}
      />
      <p className="text-xs text-muted-foreground">{hint}</p>
    </div>
  );
};

export type SimulatorPanelProps = {
  params: SimulationParams;
  onParamsChange: (params: SimulationParams) => void;
  /**
   * Story mode passes true: fewer controls, no page-level heading, and the panel
   * renders its own `SimulatorDisclaimer` because a chapter has no route shell.
   */
  compact?: boolean;
};

/**
 * The whole simulator experience in one component: the controls, the chart and the
 * plain-language explanation. `/simulator` and Story mode both mount this, which is
 * why it owns its own debounce. The chart's `ChartFrame` footnote always repeats the
 * "not a prediction" sentence, whichever way the panel is mounted.
 */
export const SimulatorPanel = ({
  params,
  onParamsChange,
  compact = false,
}: SimulatorPanelProps): React.ReactElement => {
  const [debouncedParams, setDebouncedParams] = useState<SimulationParams>(() =>
    normalizeParams(params),
  );

  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedParams(normalizeParams(params));
    }, RERUN_DEBOUNCE_MS);
    return () => clearTimeout(timer);
  }, [params]);

  const result = useMemo<SimulationResult>(
    () => runSimulation(debouncedParams),
    [debouncedParams],
  );

  const patch = (next: Partial<SimulationParams>): void => {
    onParamsChange(normalizeParams({ ...params, ...next }));
  };

  const handleNetworkStrengthChange = (value: number): void => patch({ networkStrength: value });
  const handleSwitchingCostChange = (value: number): void => patch({ switchingCost: value });
  const handleEntrantsChange = (value: number): void => patch({ entrantsPerTick: value });
  const handleShiftProbChange = (value: number): void => patch({ shiftProb: value });
  const handleTicksChange = (value: number): void => patch({ ticks: value });

  const handleSeedChange = (event: React.ChangeEvent<HTMLInputElement>): void => {
    const parsed = Number.parseInt(event.target.value, 10);
    if (Number.isNaN(parsed)) return;
    patch({ seed: parsed });
  };

  const handleNewSeed = (): void => patch({ seed: nextSeed(params.seed) });

  const handlePreset = (preset: SimulationParams): void => onParamsChange(normalizeParams(preset));

  return (
    <div className="flex flex-col gap-4">
      {/* The /simulator shell renders the banner above the Suspense boundary, so
          repeating it here would double it; a Story embed has no shell and needs
          its own. Either way the chart's footnote carries the same sentence. */}
      {compact ? <SimulatorDisclaimer /> : null}

      <div className="flex flex-col gap-4 rounded-lg border border-border bg-card p-4">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
            Presets
          </span>
          {SIMULATION_PRESETS.map((preset) => (
            <Button
              key={preset.id}
              type="button"
              variant="outline"
              size="sm"
              title={preset.description}
              onClick={() => handlePreset(preset.params)}
            >
              {preset.label}
            </Button>
          ))}
        </div>

        <div
          className={cn("grid gap-x-6 gap-y-4", {
            "sm:grid-cols-2 lg:grid-cols-3": !compact,
            "sm:grid-cols-3": compact,
          })}
        >
          <SliderControl
            id="sim-network"
            label="Network strength"
            hint="How much a firm's existing share feeds back into its appeal."
            value={params.networkStrength}
            min={0}
            max={1}
            step={0.05}
            display={params.networkStrength.toFixed(2)}
            onChange={handleNetworkStrengthChange}
          />
          <SliderControl
            id="sim-switching"
            label="Switching cost"
            hint="How hard it is to leave a vendor. At 1 nobody churns."
            value={params.switchingCost}
            min={0}
            max={1}
            step={0.05}
            display={params.switchingCost.toFixed(2)}
            onChange={handleSwitchingCostChange}
          />
          <SliderControl
            id="sim-shift"
            label="Platform-shift probability"
            hint="Chance per tick that a technology shift resets incumbent advantage."
            value={params.shiftProb}
            min={0}
            max={0.2}
            step={0.005}
            display={formatPercent(params.shiftProb * 100, 1)}
            onChange={handleShiftProbChange}
          />

          {compact ? null : (
            <>
              <SliderControl
                id="sim-entrants"
                label="Entrants per tick"
                hint="New firms arriving each tick, each with a 0.5% toehold."
                value={params.entrantsPerTick}
                min={0}
                max={3}
                step={1}
                display={String(params.entrantsPerTick)}
                onChange={handleEntrantsChange}
              />
              <SliderControl
                id="sim-ticks"
                label="Ticks"
                hint="How long the market runs. One tick is an abstract period, not a year."
                value={params.ticks}
                min={20}
                max={200}
                step={10}
                display={String(params.ticks)}
                onChange={handleTicksChange}
              />
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="sim-seed" className="text-sm">
                  Seed
                </Label>
                <div className="flex items-center gap-2">
                  <Input
                    id="sim-seed"
                    type="number"
                    inputMode="numeric"
                    min={0}
                    max={999999}
                    step={1}
                    value={params.seed}
                    onChange={handleSeedChange}
                    className="h-9 w-28 font-mono"
                  />
                  <Button type="button" variant="secondary" size="sm" onClick={handleNewSeed}>
                    <Dices aria-hidden="true" className="size-3.5" />
                    New seed
                  </Button>
                </div>
                <p className="text-xs text-muted-foreground">
                  The same seed always replays the same market.
                </p>
              </div>
            </>
          )}
        </div>
      </div>

      <SimulatorChart result={result} params={debouncedParams} />

      <div className="max-w-3xl text-sm leading-relaxed text-muted-foreground">
        <p>
          Five firms start with equal share and slightly different quality. Each tick, every firm
          becomes more attractive in proportion to the share it already holds — that is the network
          effect — while a slice of its customers churns, shrinking as switching costs rise. The
          churned customers plus a little new demand are handed out in proportion to attractiveness,
          entrants arrive with a toehold, and firms below 0.1% share are pruned. A platform shift
          cuts every incumbent&apos;s quality by 40%, drops a strong new entrant into the market and
          halves switching costs for five ticks.
        </p>
        {compact ? null : (
          <p className="mt-2">
            The concentration line is the Herfindahl-Hirschman Index: the sum of squared percentage
            shares, so a monopoly scores 10,000. Competition authorities treat 1,800 as the line
            above which a market is highly concentrated.{" "}
            <Link
              href="/methodology/#simulator"
              className="font-medium text-foreground underline underline-offset-4 hover:no-underline"
            >
              Read the full model description on the methodology page
            </Link>
            .
          </p>
        )}
        {compact ? (
          <p className="mt-2">
            <Link
              href="/methodology/#simulator"
              className="font-medium text-foreground underline underline-offset-4 hover:no-underline"
            >
              How this model works
            </Link>
          </p>
        ) : null}
      </div>
    </div>
  );
};

const paramsFromState = (state: AtlasState): SimulationParams =>
  normalizeParams({
    networkStrength: state.net,
    switchingCost: state.sw,
    entrantsPerTick: state.ent,
    shiftProb: state.shift,
    ticks: state.ticks,
    seed: state.seed,
  });

/**
 * The client half of `/simulator`: it reads the six simulator keys from the URL,
 * keeps them in local state while the reader drags a slider, and writes them back
 * with a debounced `router.replace` so a run can be shared as a link.
 *
 * It exists as its own component because `useSearchParams` forces a client bailout
 * in a statically exported app, so it has to sit inside a `<Suspense>` boundary
 * while the page around it stays a server component that can export `metadata`.
 */
export const SimulatorRoute = (): React.ReactElement => {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const [baseState] = useState<AtlasState>(() => parseAtlasState(searchParams));
  const [params, setParams] = useState<SimulationParams>(() => paramsFromState(baseState));

  useEffect(() => {
    const timer = setTimeout(() => {
      const query = serializeAtlasState(
        updateAtlasState(baseState, {
          net: params.networkStrength,
          sw: params.switchingCost,
          ent: params.entrantsPerTick,
          shift: params.shiftProb,
          ticks: params.ticks,
          seed: params.seed,
        }),
      );
      const href = query.length === 0 ? pathname : `${pathname}?${query}`;
      router.replace(href, { scroll: false });
    }, URL_DEBOUNCE_MS);

    return () => clearTimeout(timer);
  }, [baseState, params, pathname, router]);

  const handleParamsChange = (next: SimulationParams): void => setParams(next);

  return <SimulatorPanel params={params} onParamsChange={handleParamsChange} />;
};
